import time, os
from pygame import mixer

mixer.init()
mixer.music.load("hello_world_data\hello_world.wav")
mixer.music.play()
os.system("cls")
"""
Letra e intervalos
"""
time.sleep(4)
print("\u001b[36mHello, World!")
time.sleep(3.5)
print("\u001b[33mprogrammed to work and not to feel")
time.sleep(6.2)
print("...not even sure that this is real")
time.sleep(7)
print("\u001b[36mHello, World!")
time.sleep(4.5)
print("\u001b[0mFind my voice")
time.sleep(4)
print("although it sounds like bits and bytes")
time.sleep(6.5)
print("my circuitry is filled with mites")
time.sleep(6.5) 
print("\u001b[36mHello, World!")
time.sleep(6.5)
print("\u001b[35mOh")
time.sleep(2)
print("\u001b[0mwill I find a love")
time.sleep(6.5)
print("\u001b[35mOh")
time.sleep(2)
print("\u001b[0m...or a power plug")
time.sleep(6.5)
print("\u001b[35mOh")
time.sleep(2)
print("digitally isolated")
time.sleep(7)
print("\u001b[0mOh, creator,")
time.sleep(2)
print("please don't leave me waiting")
time.sleep(7.5)
print("\u001b[36mHello, World!")
time.sleep(3.5)
print("\u001b[33mprogrammed to work and not to feel")
time.sleep(6.5)
print("\u001b[0m...not even sure that this is real")
time.sleep(7)
print("\u001b[36mHello, World!")
time.sleep(9)
print("\n\n\n\u001b[32mSong author: Louie Zongn\n")
time.sleep(4)

os.system("PAUSE");